framework:
    notifier:
        chatter_transports:
            main: '%env(SLACK_DSN)% || %env(TELEGRAM_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['email', 'sms/twilio', 'chat/slack']
            high: ['email', 'sms/twilio']
            medium: ['email', 'browser']
            low: ['email']
        admin_recipients:
            - { email: admin@example.com }
